### ISSUE TITLE
New regulator for internal operation

### ISSUE THREAD

**Issue by MarkoSagadin** [IRNAS/pira-smart-2.0-hardware#7]
Old buck converter was replaced with LDO TPS783.LDO is now converting from VBAT to VCC.

**Comment by VojislavM** [comment]
This regulator will power:
* Murata LoRa module and main processor
* RTC
* EEPROM
* BT MODLE

selected LDO regulator is TPS78326DDCT with output voltage of 2.6V
Note: this could be a problem for the RTC because it has minimum operating voltage at 2.7V, but the tripping voltage for the backup battery is 2.2V. Need to test

**Comment by SloMusti** [comment]
The regulator can be changes to 2.7 or 2.8V voltage no problem. LiPo Battery protection cut-off is at 2.8V.

**Comment by VojislavM** [comment]
![image](https://user-images.githubusercontent.com/8199477/54989101-25e74100-4fb8-11e9-9a87-32d8a2afd60b.png)

Resistors R31 and R35 are seledted based on the LDO used in the design. There are several optins for the LDO from series TPS783 and TPS 780.
This way we can use fixed, dual level, or adjustable output form the regulator.
